In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
df=pd.read_csv('/content/heart.csv')
df

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0

In [ ]:
print(df.isna().sum())
print(df.isnull().any())

Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64
Age               False
Sex               False
ChestPainType     False
RestingBP         False
Cholesterol       False
FastingBS         False
RestingECG        False
MaxHR             False
ExerciseAngina    False
Oldpeak           False
ST_Slope          False
HeartDisease      False
dtype: bool

In [ ]:
df.nunique()

Age                50
Sex                 2
ChestPainType       4
RestingBP          67
Cholesterol       222
FastingBS           2
RestingECG          3
MaxHR             119
ExerciseAngina      2
Oldpeak            53
ST_Slope            3
HeartDisease        2
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             918 non-null    int64
 1   Sex             918 non-null    object
 2   ChestPainType   918 non-null    object
 3   RestingBP       918 non-null    int64
 4   Cholesterol     918 non-null    int64
 5   FastingBS       918 non-null    int64
 6   RestingECG      918 non-null    object
 7   MaxHR           918 non-null    int64
 8   ExerciseAngina  918 non-null    object
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    object
 11  HeartDisease    918 non-null    int64
dtypes: float64(1), int64(6), object(5)
memory usage: 86.2+ KB

In [ ]:
for i in df.columns:
    if(df[i].dtype=='int64'):
        df[i]=df[i].astype('int16')
    else:
        continue
df.dtypes

Age                 int16
Sex                object
ChestPainType      object
RestingBP           int16
Cholesterol         int16
FastingBS           int16
RestingECG         object
MaxHR               int16
ExerciseAngina     object
Oldpeak           float64
ST_Slope           object
HeartDisease        int16
dtype: object

In [ ]:
df.describe()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease
count,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000
mean,53.510893,132.396514,198.799564,0.233115,136.809368,0.887364,0.553377
std,9.432617,18.514154,109.384145,0.423046,25.460334,1.066570,0.497414
min,28.000000,0.000000,0.000000,0.000000,60.000000,-2.600000,0.000000
25%,47.000000,120.000000,173.250000,0.000000,120.000000,0.000000,0.000000
50%,54.000000,130.000000,223.000000,0.000000,138.000000,0.600000,1.000000
75%,60.000000,140.000000,267.000000,0.000000,156.000000,1.500000,1.000000
max,77.000000,200.000000,603.000000,1.000000,202.000000,6.200000,1.000000

In [ ]:
df.shape

(918, 12)

In [ ]:
df.Sex.value_counts()

Sex
M    725
F    193
Name: count, dtype: int64

In [ ]:
chest_count=df.ChestPainType.value_counts()
print(chest_count)

ChestPainType
ASY    496
NAP    203
ATA    173
TA      46
Name: count, dtype: int64

In [ ]:
df.Cholesterol.describe()

count    918.000000
mean     198.799564
std      109.384145
min        0.000000
25%      173.250000
50%      223.000000
75%      267.000000
max      603.000000
Name: Cholesterol, dtype: float64

In [ ]:
pd.crosstab(df.Sex,df.FastingBS)

FastingBS    0    1
Sex
F          167   26
M          537  188

In [ ]:
df.RestingECG.value_counts()

RestingECG
Normal    552
LVH       188
ST        178
Name: count, dtype: int64

In [ ]:
df.groupby('Sex')[['RestingBP', 'Cholesterol','MaxHR']].agg({'mean','std','median'})

    RestingBP                        Cholesterol                          \
       median        std        mean      median         std        mean
Sex
F       130.0  19.392638  132.212435       243.0   85.195441  241.196891
M       130.0  18.286739  132.445517       219.0  112.351444  187.513103

     MaxHR
    median        std        mean
Sex
F    150.0  22.154902  146.139896
M    134.0  25.719191  134.325517

In [ ]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split, GridSearchCV

from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
le=LabelEncoder()
df

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0

In [ ]:
df["Sex"]=le.fit_transform(df["Sex"])
df["ChestPainType"]=le.fit_transform(df["ChestPainType"])
df["RestingECG"]=le.fit_transform(df["RestingECG"])
df["ExerciseAngina"]=le.fit_transform(df["ExerciseAngina"])
df["ST_Slope"]=le.fit_transform(df["ST_Slope"])
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,1,1,140,289,0,1,172,0,0.0,2,0
1,49,0,2,160,180,0,1,156,0,1.0,1,1
2,37,1,1,130,283,0,2,98,0,0.0,2,0
3,48,0,0,138,214,0,1,108,1,1.5,1,1
4,54,1,2,150,195,0,1,122,0,0.0,2,0

In [ ]:
x=df.drop(columns='HeartDisease')
y=df.HeartDisease
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.3)

***SVM***

In [ ]:
model_svm = SVC(kernel = 'linear', random_state = 0)
model_svm.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

In [ ]:
y_pred = model_svm.predict(X_test)

In [ ]:
accuracy_svm = accuracy_score(y_test, y_pred)
print(accuracy_svm)

0.8369565217391305

In [ ]:
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import uniform


param_dist = {
    'C': (0.1,1,10,100),
    'kernel': ['linear', 'rbf','poly'],
    'gamma': ['scale'],
    'degree': [3,4,5]
}

random_search = RandomizedSearchCV(SVC(), param_distributions=param_dist, n_iter=10, cv=3, n_jobs=-1, verbose=1)
random_search.fit(X_train, y_train)

print("Best parameters:", random_search.best_params_)

Fitting 3 folds for each of 10 candidates, totalling 30 fits
Best parameters: {'kernel': 'linear', 'gamma': 'scale', 'degree': 5, 'C': 1}

In [ ]:
best_svm = random_search.best_estimator_


y_pred_best = best_svm.predict(X_test)

accuracy_best = accuracy_score(y_test, y_pred_best)
print(f"Accuracy of the model after Hyperparameter Tuning: {accuracy_best}")


print("Classification Report for the best model:")
print(classification_report(y_test, y_pred_best))

print("Confusion Matrix for the best model:")
print(confusion_matrix(y_test, y_pred_best))

Accuracy of the model after Hyperparameter Tuning: 0.8369565217391305
Classification Report for the best model:
              precision    recall  f1-score   support

           0       0.78      0.83      0.80       111
           1       0.88      0.84      0.86       165

    accuracy                           0.84       276
   macro avg       0.83      0.84      0.83       276
weighted avg       0.84      0.84      0.84       276

Confusion Matrix for the best model:
[[ 92  19]
 [ 26 139]]

***KNN***

In [ ]:

from sklearn.neighbors import KNeighborsClassifier


knn = KNeighborsClassifier(n_neighbors=4)

knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)

In [ ]:

accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy of the basic KNN model: {accuracy}")


print("Classification Report:")
print(classification_report(y_test, y_pred))


print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy of the basic KNN model: 0.644927536231884
Classification Report:
              precision    recall  f1-score   support

           0       0.54      0.84      0.65       111
           1       0.83      0.52      0.63       165

    accuracy                           0.64       276
   macro avg       0.68      0.68      0.64       276
weighted avg       0.71      0.64      0.64       276

Confusion Matrix:
[[93 18]
 [80 85]]

In [ ]:
from sklearn.model_selection import GridSearchCV

param_grid = {
    'n_neighbors': list(range(1, 51, 2)),
     'weights': ['uniform', 'distance'],
     'metric': ['euclidean', 'manhattan', 'minkowski'],
      'p': [1, 2]
}


grid_search = GridSearchCV(estimator=KNeighborsClassifier(), param_grid=param_grid, cv=5, n_jobs=-1, verbose=1)

grid_search.fit(X_train, y_train)

Fitting 5 folds for each of 300 candidates, totalling 1500 fits

GridSearchCV(cv=5, estimator=KNeighborsClassifier(), n_jobs=-1,
             param_grid={'metric': ['euclidean', 'manhattan', 'minkowski'],
                         'n_neighbors': [1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21,
                                         23, 25, 27, 29, 31, 33, 35, 37, 39, 41,
                                         43, 45, 47, 49],
                         'p': [1, 2], 'weights': ['uniform', 'distance']},
             verbose=1)

In [ ]:

print("Best Hyperparameters:", grid_search.best_params_)

best_knn = grid_search.best_estimator_

y_pred_best = best_knn.predict(X_test)

accuracy_best = accuracy_score(y_test, y_pred_best)
print(f"Accuracy of the model after Hyperparameter Tuning: {accuracy_best}")

print("Classification Report for the best model:")
print(classification_report(y_test, y_pred_best))

print("Confusion Matrix for the best model:")
print(confusion_matrix(y_test, y_pred_best))

Best Hyperparameters: {'metric': 'manhattan', 'n_neighbors': 27, 'p': 1, 'weights': 'distance'}
Accuracy of the model after Hyperparameter Tuning: 0.6992753623188406
Classification Report for the best model:
              precision    recall  f1-score   support

           0       0.59      0.80      0.68       111
           1       0.83      0.63      0.71       165

    accuracy                           0.70       276
   macro avg       0.71      0.72      0.70       276
weighted avg       0.73      0.70      0.70       276

Confusion Matrix for the best model:
[[ 89  22]
 [ 61 104]]